### ISSUE TITLE
Should the object ROM() exist?

### ISSUE THREAD

**Issue by aaronuv** [aaronuv/arby#6]
The rationale is that the user may want to add a basis pulled from the hat and the present way to do this is:
```
model = ROM()
model.basis = user_basis
```
Eventually the user may want to perform integrals with this basis, such as projections, dot products or whatever. In that case, he needs to provide the `physical_interval` (which has to be re-named). So my initial solution (probably it does not resolve this "design problem" in the most graceful way) is to force the parameter input `physical_interval` and then the class will not be initiated empty. Suggestions?

**Comment by leliel12** [comment]
short answer **yes**

long answer. The problem is the intermediate state of design between "structured" and "oo" programming. IMHO it's a model, has state so: OO is the way to go in Python.

Maybe we can check another apis like  dict. Dict has two constructors

1. The classical withe full data `dict(a=1)` or the syntactic sugar `{"a": 1}`
2. The `fromkeys` class-method: `dict.fromkeys("a")` (equivalent to `{"a": None}`

This approach is used in multiple scenarios like numpy (implemented with an external function but the behavior is the same), `np.ndarray(--bytes--)` or the function `np.array`; and several databases managers (`from_url` is classic in this domain)

Maybe something like: `ROM.from_basis` is the solution.
